### ISSUE TITLE
菜单显示异常

### ISSUE THREAD

**Issue by 44zs44** [uncarbon97/helio-admin-vue-vben#22]
![image](https://github.com/uncarbon97/helio-admin-vue-vben/assets/86179743/7d9235ab-4891-4b6c-a52e-2726ae86217d)
当选择顶部菜单模式时，菜单名称显示成了ID

**Comment by uncarbon97** [comment]
哦吼，确认了一下，可能是跟随源项目更新的时候，源项目有改动导致不适配了
个人测试的时候只试验了默认的左侧菜单……
我也不是专业前端，我试着解决一下这个问题……

**Comment by 44zs44** [comment]
src/components/Menu/src/components/MenuItemContent.vue:22

const getI18nName = computed(() => t(props.item?.meta?.title || props.item?.name));
这样就解决了

**Comment by uncarbon97** [comment]
> src/components/Menu/src/components/MenuItemContent.vue:22
> 
> const getI18nName = computed(() => t(props.item?.meta?.title || props.item?.name)); 这样就解决了

好的，我记录一下，用开发机的时候订正发个fix版
谢谢你的issue！
