### ISSUE TITLE
看了下演示站，点击菜单路由跳转，页面没有展示出来，是不是bug

### ISSUE THREAD

**Issue by MikuBlog** [uncarbon97/helio-admin-vue-vben#23]
<img width="1405" alt="image" src="https://github.com/uncarbon97/helio-admin-vue-vben/assets/43233731/43f3e99a-bef0-42cd-a58c-1fb49565acd8">

**Comment by uncarbon97** [comment]
哦吼…… 没想到构建上去出问题了…… 我排查看一下……
先回退到旧版了，可以正常渲染

**Comment by uncarbon97** [comment]
确定了发现是不同开发机node版本差异导致的，emmm
顺便更新了README里的node版本来确保成功率

谢谢你的issue！
