### ISSUE TITLE
在新增表单中的必填字段，按退格键会把表单卡死

### ISSUE THREAD

**Issue by roymax** [uncarbon97/helio-admin-vue-vben#3]
问题重现：

进入演示站
https://helio-demo.uncarbon.cc/#/dashboard/analysis/index

进入角色管理（或其他），点击「新增」，在名称中输入任意值，按退格键，浏览器(Edge/ Safari )出现卡死。

开发者模式没有这个问题，当使用生产环境编译后会出现

**Comment by uncarbon97** [comment]
emmm
我直接在我自己演示站试验了，输入值后，按退格键（ Backspace ）没有出现这个情况……

相关UA：
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by moalamri** [comment]
He's right,
If you hit backspace to empty the field the whole UI will freeze.
This happens to Edge.

**Comment by roymax** [comment]
我也没找到原因，升级了 Vben 解决问题
